name: C/C++ CI
# runs-on: self-hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # say-hello:
  #   runs-on: self-hosted
  #   steps:
  #     - run: echo "Hello World!"
  #     - run: pwd


  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: check_evv
      run: cd bike_computer_v3 && ls

    - name: cmake
      run: cd bike_computer_v3 && make cmake

    - name: make
      run: cd bike_computer_v3 && make all

  warings:
    needs: [build]
    runs-on: self-hosted
    steps:
    - name: check_log
      run: cd bike_computer_v3 && make warnings
