name: C/C++ CI
# runs-on: self-hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
<<<<<<< HEAD

  say-hello:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World!"
      - run: pwd


  build:
=======

  say-hello:
    runs-on: self-hosted
    steps:
      - run: echo "Hello World!"
      - run: pwd


  build:

>>>>>>> 58c50a2... test
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
#    - name: configure
#    run: ./configure
    - name: make
      run: cd bike_computer_v3 && make all
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
