name: host CI
# runs-on: self-hosted

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: tests-on-target-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_test_host:
    # needs: [build]
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: placeholder
      run: echo "placeholder"
    # - name: download pico-sdk
    #   uses: actions/checkout@master
    #   with:
    #     repository: raspberrypi/pico-sdk
    #     path: ./pico-sdk
    #     submodules: 'true'
    #     # recursive

    # - name: export path
    #   run: ls /tmp && ls && pwd && export PICO_SDK_PATH=./pico-sdk $$ echo $PICO_SDK_PATH

  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: fetch submodules
  #     run: |
  #       git submodule sync
  #       git submodule update --init --recursive

  #   - name: build cmake for host
  #     run: cd bike_computer_v3 && make cmake H=1

  #   - name: build host
  #     run: cd bike_computer_v3 && make all


  # test_host:
  #   needs: [build_test_host]
  #   runs-on: self-hosted
  #   steps:
  #   - name: run tests on host
  #     run: cd bike_computer_v3 && make ctest
